### ISSUE TITLE
Asset B Value Error in a Live Trade

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Superalgos#235] opened 2020-05-23 18:01 UTC
During a Live Trade, the value of Asset B suddenly changed. The change occurred when going from May 21 to May 22, exactly at midnight. You can watch the video in the 1 hour time frame and then you can watch the video in 1 minute candles to detect the exact moment.
[Archive.zip](https://github.com/Superalgos/Superalgos/files/4672263/Archive.zip)

**Comment by Luis-Fernando-Molina** [comment] 2020-05-27 13:40
Hi, this is confirmed to be a bug on Live trades with a time frame < 1hs. I will be fixed at Beta 6 version. Avoid for now Live trade with time frame under 1hs.

**Comment by julian-molina** [comment] 2020-05-27 16:36
This bug (still under investigation) has significant implications:

* It is not safe to trade live on time frames below 1H until the bug is removed.

* It may take a while for the bug to be removed, as @Luis-Fernando-Molina is already working on an upgrade of the trading engine and the bug will be removed on that version only.

* Both WHB and BBTB strategies are backtested on the 1h time frame, but live trading is usually done on the 1-minute time frame. This time frame is currently not safe, due to the known bug.

* Running a live trading session on the 1H time frame is safe in regards to the bug, as the bug does not affect this time frame.

* However, it is important to understand that when a live trading session runs on the 1H time frame, it only evaluates the take profit and stop-loss targets once per hour. This may result in a much larger slippage at the time of closing the trade.

**Comment by julian-molina** [comment] 2020-06-01 00:15
Testing a live trade taking position prior to the change in date, and closing the following day.

Position taken:

![image](https://user-images.githubusercontent.com/13994516/83365776-fd708900-a3aa-11ea-9e40-d0ab1ddc80ac.png)

Past 00:00:00

![image](https://user-images.githubusercontent.com/13994516/83365893-e41c0c80-a3ab-11ea-90d8-0f8e32d9b71a.png)

![image](https://user-images.githubusercontent.com/13994516/83365934-2cd3c580-a3ac-11ea-9586-887830139315.png)

![image](https://user-images.githubusercontent.com/13994516/83366039-be433780-a3ac-11ea-8347-72ed806d2591.png)

Position closed:

![image](https://user-images.githubusercontent.com/13994516/83366058-ecc11280-a3ac-11ea-8d05-20fdf516b076.png)

Exchange TRXs:

![image](https://user-images.githubusercontent.com/13994516/83366100-31e54480-a3ad-11ea-87d3-cddb01330049.png)

Test Logs:

[TEST LOGS.zip](https://github.com/Superalgos/Superalgos/files/4708740/TEST.LOGS.zip)

Simulation:

[Trading-Simulation.zip](https://github.com/Superalgos/Superalgos/files/4708745/Trading-Simulation.zip)

**Comment by julian-molina** [comment] 2020-06-01 18:08
The issue can not be reproduced on Superalgos Beta 5, hence, the case is closed for the time being.

**Closed by julian-molina** 2020-06-01 18:08 UTC
Labels: bug
