### ISSUE TITLE
Tutorials progress not working properly

### ISSUE THREAD

**Issue by MojoMoe** [Superalgos/Superalgos#327] opened 2021-01-07 10:36 UTC
In Beta 8 when I am using the Tutorials navigation box and click on 'previous' a few times, then click on 'stop', then when I 'resume' the tutorials, it takes me to the progress position I was in before I had clicked on 'previous'. Not sure if this is the expected behaviour or not. I would have thought it would resume from where I had clicked on 'stop' because that is where I would like to resume from, the next time I reopen the tutorials.

**Comment by julian-molina** [comment] 2021-01-07 12:21
What you describe is the expected behavior at this point. The reasoning is that the Resume option takes you to the furthest point you have already covered, so that you may continue with the still undiscovered bits.

Also, if you skip steps, the Resume option takes you to the earliest step you skipped, as it is marked as not done.

**Comment by Luis-Fernando-Molina** [comment] 2021-01-15 15:45
As Julian said, this is the criteria as of today.

**Closed by Luis-Fernando-Molina** 2021-01-15 15:45 UTC
