### ISSUE TITLE
Improve the UI responsive when switching workspace

### ISSUE THREAD

**Issue by anvd** [Superalgos/Superalgos#311] opened 2020-12-27 08:22 UTC
## Context
I have problem when switching workspaces in Superalgos.
The context is that on the develop branch, after finishing the tutorial series on “Trading System Design Tutorials” workspace, I have switched to “Weak-hands Buster V2 plug-in” workspace. The Chrome UI is not responsive

**Operating System:** Frontend runs on MacOs, Backend runs on Ubuntu.

**Software version:** Develop branch, commit a3c07edc9

**Workspace version:** “Trading System Design Tutorials” and “Weak-hands Buster V2”

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.
I guess that after running through the tutorial series, the “Trading System Design Tutorials” workspace has been filled with a lot of data. It may thus take more time to switch workspaces. It would be useful if Superalgos can inform this information on the UI (e.g., using some kinds of progressive UI/UX) so that the user knows that the switch workspace process is running in the backend.

### 2. Clearly explain what you wish to accomplish.
I can switch workspaces successfully.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1. Finish the tutorials in the “Trading System Design Tutorials” workspace.
2. Switch to "Weak-hands Buster V2" workspace.

### 4. Explain what is the result you expect from your actions.
The workspace is successfully switched and the tutorial is displayed.

### 5. Explain what happens instead of the expected results.

Chrome is not responsive.
![switch_failed](https://user-images.githubusercontent.com/12640348/103166612-79a25080-4856-11eb-9545-e3b5d01d1d36.png)

Restart Superalgos, the workspace seems have been broken.
![Screen Shot 2020-12-27 at 1 30 18 PM](https://user-images.githubusercontent.com/12640348/103166643-c5ed9080-4856-11eb-959d-21b7b5464c70.png)

However, on a Superalgos fresh installation, I can switch to "Weak-hands Buster V2" in the first launch.
![fresh_workspace](https://user-images.githubusercontent.com/12640348/103166676-1bc23880-4857-11eb-9886-aa6f45c6dd6e.png)

**Comment by cozed-gh** [comment] 2020-12-29 20:50
Havn't got a better explanation rather than that I experience the same as above.
Backend: Raspberry Pi (raspian, 4gb ram, running minMemo noBrowser)
Frontend: Windows 10, Chrome
Problem: Same as above - Once in a while I get to a point where the page freezes or "something" happens where i need to reload the workspace, and the project disappears/ GUI gets broken (exactly as above picture). I can reload any other plugin, and get back to the "normal" GUI, but when I try to reload the autosaved workspace from "My-Workspaces", it is still "broken".

**Comment by anvd** [comment] 2020-12-30 00:06
That's right I can reload the original plugin workspace. But the workspace copied to "My-Workspaces" seems to be broken.

**Comment by Luis-Fernando-Molina** [comment] 2020-12-30 08:00
Can you please switch to the develop branch and use the system there? There are some fixes there to that problem that i would like to know if they work for you. Currently I am not reproducing that behavior, but I am at the develop branch. If it still happens to you in develop again, please let me know.

**Comment by cozed-gh** [comment] 2020-12-30 14:39
(havn't looked into switching into dev branch yet)
Shooting from the hip here - But I get the feeling that it has some problems saving changes (might be related to privleges)
I got "There was a problem saving..." in the bar between design and charting space.
Tried to copy an existing, functioning workspace within "My-Workspaces" as my user - but I couldn't 'cp' it without 'sudo'. So I figured I might try to start Superalgos with 'sudo'. Didn't make any difference.
Started Superalgos as 'root' - but I'm still missing some changes I made yesterday. (I know it's a rule of thumb never to be logged in as root consistently)
Yesterday I was quite hammering Ctrl+Shift+S to make sure it said "Saved". 
Is there any log where I can see these "Problem saving" errors - So we get some more info.

**Comment by julian-molina** [comment] 2020-12-30 15:32
"Conclusion - Some things get saved, some not."

About that note, that is actually true and to be expected. This is the thing: data structures that are included in the workspace as plugins may not be modified and saved at the workspace level.

To modify a data structure it must be part of the workspace (dragged and dropped into the workspace).

Take a look at this part of the docs: https://docs.superalgos.org/suite-hierarchy-plugins.html#plugins

I don't know if that may be part of your issue or not. It depends on what you've done with your workspace and what structures it is you are trying to modify and save.

**Comment by cozed-gh** [comment] 2020-12-30 15:48
Well, I did manage to drag and drop Zeus into the workspace - and it's still there today.
After I added Zeus, I managed to build my stategy with it - Detaching 'Xtreme', and just edited the other one to my needs, using Zeus (DMI in this case).
Zeus Data Mine is still there, but all Strategy work is lost.

This is in a workspace that's in "My-Workspaces" - saved from a plugin (wanted something to build from) - so I get the picture faster. :)

**Comment by julian-molina** [comment] 2020-12-30 16:00
That would be consistent with the expected behavior provided that the trading system you were working on is included as a plugin. If that is the case, to avoid loosing further work you must:

1. Clone the trading system.
2. Remove the Plugin File reference (so that the trading system is not included again every time you reload the page).
3. Delete the included trading system.
4. Restore the clone on the workspace (drag and drop the cloned file on the design space).
5. Work on the cloned data structure, which is now part of the workspace.

Either way, this doesn't seem to be related to the issue reported in the OP. If you have any further difficulties with this, drop by the [Telegram Support Group](https://t.me/superalgossupport) so that we can work it out.

**Comment by cozed-gh** [comment] 2020-12-30 16:09
Brilliant Julian!
You're right - this might be off topic.
However I didn't get that OP issue when starting the session as root yesterday, the day before that I got it several times (3-4 times during a 5h "trying to figure things out"-session).

**Comment by julian-molina** [comment] 2020-12-30 17:00
Regarding permissions, if you place the Superalgos folder in a location where the logged-on user has write permissions, you shouldn't need to run as admin or root.

**Comment by Luis-Fernando-Molina** [comment] 2020-12-30 17:57
What I can add here is that there was a bug that was difficult to chase because it did not happen often and was difficult to reproduce, that saved the workspace with almost an empty file. That is the one that might have been solved in develop. Based on all the difficulties I see, I will probably take some time and make some changes to the workspace managment:

1. I want to stop calling Plugin Workspaces and replace those for Template workspaces, because they do not behave like all the other plugins.  
2. I would make the automatic saving to writhe the file with a different name than when you save it with CTRL + S, like adding -backup to the name for instance. 
3. Probably I go as far as changing the UI of the Workspaces Tab, since it is confusing to have both 'plugins' and 'my workspaces' together. 
Hope after a few days spent there all this will behave better.  :-)

**Comment by Luis-Fernando-Molina** [comment] 2020-12-30 17:59
4. Making the UI more responsive while switching workspaces.

**Comment by anvd** [comment] 2020-12-30 22:37
Here is how I reproduce the behaviour.
Environment: Backend runs on Ubuntu 20.04. Access the backend using Chrome running on MacOS.
I’m on develop branch, commit f24796c32

Steps:
1. SSH to the Ubuntu machine and launch Superalgos with “node run noBrowser”
2. Access Superalgos from MacOS, change the ip address in the Network Node to point to the Ubuntu machine.
3. Switch to “Plugin -> Weak-Hands-Buster v2” workspace, change the ip address in the Network Node to point to the Ubuntu machine.
4. Close Chrome
5. Open Chrome and access SuperAlgos. The workspace is showed with only one “Weak-hands Buster v2” icon. All other icons disappear. Of course, I can reload the “Plugin -> Weak-Hands-Buster v2” workspace to make everything work again.
<img width="1336" alt="Screen Shot 2020-12-31 at 5 25 54 AM" src="https://user-images.githubusercontent.com/12640348/103384769-28ca7a80-4b2a-11eb-8dc2-3c71ae04832b.png">

**Comment by anvd** [comment] 2021-01-10 05:20
I would love to test these changes as soon as they are available :-)

**Comment by Luis-Fernando-Molina** [comment] 2021-01-15 15:52
Ok, I managed to work on the UI responsiveness while switching workspaces. I think that now is responsive enough, if not, let me know. I will close this issue for now, and open 3 others related to other tasks I said I would do some day.

Changes are available at the develop branch.

>I want to stop calling Plugin Workspaces and replace those for Template workspaces, because they do not behave like all the other plugins.
>I would make the automatic saving to writhe the file with a different name than when you save it with CTRL + S, like adding -backup to the name for instance.
>Probably I go as far as changing the UI of the Workspaces Tab, since it is confusing to have both 'plugins' and 'my workspaces' together.
Hope after a few days spent there all this will behave better. :-)

**Closed by Luis-Fernando-Molina** 2021-01-15 15:52 UTC
