### ISSUE TITLE
Docker container crashes on UI startup

### ISSUE THREAD

**Issue by jb33k** [Superalgos/Superalgos#1270] opened 2021-07-05 16:05 UTC
I'm trying to testdrive the system using the docker instructions provided in the README but as soon as I reach the `Setting up docs search engine` message, container crashes with the following message:
```
[ERROR] Error reading current branch.
Error: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GitExecutorChain.onFatalException (/app/Client/node_modules/simple-git/src/lib/runners/git-executor-chain.js:61:87)
    at GitExecutorChain.<anonymous> (/app/Client/node_modules/simple-git/src/lib/runners/git-executor-chain.js:52:28)
    at Generator.throw (<anonymous>)
    at rejected (/app/Client/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
[ERROR] Client -> client-> unhandledRejection -> reason = {}
[ERROR] Client -> client-> unhandledRejection -> p = {}
```

The UI does load pass the docs search engine message, but images are broken because docker container is down. If I restart it, some images work but most not. I'm getting these errors:

```
[ERROR] httpInterface -> respondWithImage -> onFileRead -> File Not Found: ./Projects/Foundations/Icons/en.png or Error = Error: ENOENT: no such file or directory, open './Projects/Foundations/Icons/en.png'
[ERROR] httpInterface -> respondWithImage -> onFileRead -> File Not Found: ./Projects/Foundations/Icons/bullet/bullet-warning.png or Error = Error: ENOENT: no such file or directory, open './Projects/Foundations/Icons/bullet/bullet-warning.png'
```

docker 18.09.7 on Ubuntu 18.04, but that shouldn't matter because this is docker after all.

**Comment by harrellbm** [comment] 2021-07-06 17:24
Have you brought up this issue on any of the telegram channels? I'm pretty sure the devs working on docker have been putting in patches to fix things like this.

**Comment by jb33k** [comment] 2021-07-08 09:09
@harrellbm No because I thought this was the right channel to report issues.

**Comment by harrellbm** [comment] 2021-07-08 17:25
Issues are a good place to put feature requests but the dev channels on telegram or discord are a much better place to collaborate and get issues like this taken care of faster.  A lot more of the devs will see and pick up issues reported there.

**Comment by harrellbm** [comment] 2021-07-10 14:25
@jb33k I just got in contact with the devs working on the docker image.  They are looking into this now.  If you want to join the conversation it is happening on the Superalgos Discord server in the developers chat.

**Comment by ssplatt** [comment] 2021-07-11 16:59
if you are trying to using one of the latest develop branch builds then it's probably got something to do with the fact that there is no "git" environment in the docker container and some of the commits recently are about saving the git branch into the UI application.

**Comment by ssplatt** [comment] 2021-07-12 19:06
I think this merge is why the error is occurring. https://github.com/Superalgos/Superalgos/pull/1262. if you pull the container tagged `268d5eba7ca6c7d9814369668a9602de85ea0ca0` (the commit before that merge) I think you'll see you don't receive the error anymore. Of course, keep in mind that the docker container doesn't have git things in it so you won't be able to switch between branches or commit changes. The docker container is intended to be used for "production" deployments.

**Comment by ssplatt** [comment] 2021-07-14 13:42
I've started working on a fix that will check if `git` is installed before trying to do "git" things.

**Comment by ssplatt** [comment] 2021-07-15 15:14
a fix was merged. can you confirm you are not experiencing crashes anymore?

**Comment by mercadeoweb** [comment] 2021-07-16 00:36
Not crash but log show an error: [ERROR] `git` not installed.

**Comment by ssplatt** [comment] 2021-07-16 00:52
Yes that's intentional.

**Comment by mercadeoweb** [comment] 2021-07-16 02:10
[ERROR] `git` not installed.
[ERROR] httpInterface -> respondWithImage -> onFileRead -> File Not Found: ./Projects/Foundations/Icons/en.png or Error = Error: ENOENT: no such file or directory, open './Projects/Foundations/Icons/en.png'
[ERROR] httpInterface -> respondWithImage -> onFileRead -> File Not Found: ./Projects/Foundations/Icons/bullet/bullet-warning.png or Error = Error: ENOENT: no such file or directory, open './Projects/Foundations/Icons/bullet/bullet-warning.png'
[ERROR] httpInterface -> respondWithImage -> onFileRead -> File Not Found: ./Projects/Foundations/Icons/bullet/bullet-warning.png or Error = Error: ENOENT: no such file or directory, open './Projects/Foundations/Icons/bullet/bullet-warning.png'

**Comment by harrellbm** [comment] 2021-07-16 03:25
You will need to install git for things to work correctly.  There are instructions in the readme to help you out.

**Comment by mercadeoweb** [comment] 2021-07-16 10:28
Is not possible, because running shell command from Docker container, show..

$ apt-get install git-all
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

sudo is not installed, maybe do you need add command to Dockerfile on Image?

**Comment by ssplatt** [comment] 2021-07-16 11:16
It is intentional that git isn't installed and that it isn't able to be installed. The docker images are intended to be immutable so the code and other packages are not supposed to change once the image is built. They are meant for production-like deployment where consistency, predictability, and reproducibility are key.

What steps are you taking to get the image errors? I cannot reproduce that right now. Are you using a brand new workspace?

**Comment by mercadeoweb** [comment] 2021-07-16 11:37
Images errors with Tutorial (flags and icons)

**Comment by tty666** [comment] 2021-08-03 11:53
Hey guys I have the same behavior, please just consider that the docker image is not working currently, could someone have a look and fix it ?
We have the message "The UI is loading..." on the browser port 34248, we have the message "Upgrade Required" on the browser port 18041.
And that's it ... not working.
could you update with a new docker image and share with us the url ( I tested latest and develop both has the same issue ... )

**Comment by ssplatt** [comment] 2021-08-03 13:31
I can't reproduce either of these issues. Can you provide some more information please?

Operating system:
Output of `docker image ls`:
command executed to start the container:
output of `docker ps -a` after starting the container:
output of `docker logs` after starting the container:

**Comment by ssplatt** [comment] 2021-08-04 20:33
I think this issue can be closed now since these secondary issues are not actual "Docker container crashes". If the other issues persist please open new issues or ask for assistance in Telegram or Discord.

**Comment by Luis-Fernando-Molina** [comment] 2021-08-05 08:21
good job @ssplatt !!!

**Closed by Luis-Fernando-Molina** 2021-08-05 08:21 UTC

**Comment by tty666** [comment] 2021-08-05 17:07
I found the problem anyway it was the ad blocker uBlock Origin blocking scripts and freezing the page on this message.
Thanks for the support
