### ISSUE TITLE
Cant startup correctly after following the tutorial for commiting profile.

### ISSUE THREAD

**Issue by gitforkgit** [Superalgos/Superalgos#2028] opened 2021-10-02 15:24 UTC
## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:**Linux (ubuntu 20.4)    All the software required(chrome,node are up to date)

**Software version:** today's master branch | today's develop branch (dont know because of the trouble)

**Workspace version:** My custom workspace (superalgos token workspace saved as mine, as mentioned in the tutorial)

**Reproducible:** the issue may reproduced.

### 1. Explain what the problem seems to be.

I followed the tutorial for commiting my user profile. It said to switch the branch. I clicked on the link in the footer as it was explained. Then a window popped up that said i need to restart the ui and the superalgos itself. I closed the terminal and the UI. Then i restarted it and typed in: node platform. Everything seemed to work fine(the window popped up and started loading)
The terminal gave back this:(I changed the name of my pc and the ports for privacy reasons, but they are as usual)

my-pc:~/Superalgos$ node platform

Total RAM istalled in this system is ........................ 9.69 GB 
Total RAM available for Superalgos is ....................... 8.23 GB

If you would like to enable less RAM than that, use the minMemo flag. Note: RAM will be allocated only if needed.

OPTIONS ACCEPTED:

none ........................................................ Running without any command line options.

SUPERALGOS PLATFORM CLIENT SERVERS:

Web Server .................................................. Started
UI File Server .............................................. Started
Project File Server ......................................... Started
Plugin Server ............................................... Started
Data File Server ............................................ Started
Events Server ............................................... Started
Task Manager Server ......................................... Started
CCXT Server ................................................. Started
WEB3 Server ................................................. Started
Github Server ............................................... Started

SUPERALGOS PLATFORM CLIENT INTERFACES:

Web Sockets Interface ....................................... Listening at port (edit: usual ports)
Http Interface .............................................. Listening at port        (edit: usual ports)

You are running Superalgos Beta 11

What's new? These are the main new features in this version:

Governance System ........................................... Automates the distribution of SA Tokens and allow users to vote on the direction of the project.
TensorFlow Integration ...................................... Allows creating and training ML models and use them in trading strategies.

What's next? This is the current development pipeline:

Superalgos P2P Network ...................................... Will allow algo-traders to share trading signals with Superalgos users consuming these signals via a mobile app.
Real-time Trading Signals ................................... Will allow users to emit trading signals and be rewarded with SA Tokens.
Superalgos Mobile ........................................... Will allow users to consume trading signals for free and autonomously execute trades from their mobile phones.
Ethereum Integration ........................................ Will allow mining data from an Ethereum network node, and bring it into the Superalgos workflow.

[WARN] getPluginFileContent -> File not Found -> Path = ./Projects/Governance/Plugins/Assets/Superalgos-PL.json
[ERROR] httpInterface -> LoadPlugin -> Method call produced an error.
[ERROR] httpInterface -> LoadPlugin -> err.stack = Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at respondWithEmptyArray (mypc /Superalgos/Projects/Foundations/SA/Utilities/HttpResponses.js:107:22)
    at Object.respondWithContent (/mypc /Superalgos/Projects/Foundations/SA/Utilities/HttpResponses.js:59:13)
    at processRequest (mypc /Superalgos/Platform/Client/httpInterface.js:1391:81)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[ERROR] httpInterface -> LoadPlugin -> Params Received = undefined
[ERROR] Platform App -> unhandledRejection -> reason = {"code":"ERR_HTTP_HEADERS_SENT"}
[ERROR] Platform App -> unhandledRejection -> p = {}
mypc :~/Superalgos$ 

### 2. Clearly explain what you wish to accomplish.

Use Superalgos as before with all my workspaces, and commit my user profile.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.
I followed the tutorial for commiting my user profile. It said to switch the branch. I clicked on the link in the footer as it was explained. Then a window popped up that said i need to restart the ui and the superalgos itself. I closed the terminal and the UI. Then i restarted it and typed in: node platform

### 4. Explain what is the result you expect from your actions.

That superalgos switched branches and i can finally commit my user profile.

### 5. Explain what happens instead of the expected results.

The Ui is stuck loading the plugins and the terminal gives me back errors and warnings.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

[WARN] getPluginFileContent -> File not Found -> Path = ./Projects/Governance/Plugins/Assets/Superalgos-PL.json
[ERROR] httpInterface -> LoadPlugin -> Method call produced an error.
[ERROR] httpInterface -> LoadPlugin -> err.stack = Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at respondWithEmptyArray (mypc /Superalgos/Projects/Foundations/SA/Utilities/HttpResponses.js:107:22)
    at Object.respondWithContent (/mypc /Superalgos/Projects/Foundations/SA/Utilities/HttpResponses.js:59:13)
    at processRequest (mypc /Superalgos/Platform/Client/httpInterface.js:1391:81)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[ERROR] httpInterface -> LoadPlugin -> Params Received = undefined
[ERROR] Platform App -> unhandledRejection -> reason = {"code":"ERR_HTTP_HEADERS_SENT"}
[ERROR] Platform App -> unhandledRejection -> p = {}

**Comment by harrellbm** [comment] 2021-10-03 11:16
This error should be fixed in the develop branch.  You will need to run git fetch upstream to make sure you pull in the patch.  If you need help running that command you can hope into one of the telegram channels or discord and someone will be available to help

**Comment by ssplatt** [comment] 2021-11-16 02:27
duplicate of https://github.com/Superalgos/Superalgos/issues/1788

**Closed by ssplatt** 2021-11-16 02:27 UTC
Labels: bug, Governance
